apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gda-agentops-sandbox

resources:
  - service-monitor.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: gis-data-agent
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/environment-profile: temporal-agentops-discovery-observability
