"""
Intrinsic Motivation Engine — autonomous task discovery and prioritization (v22.0).

Implements SIGMOD 2026 L4 capability S-9: internal reward signals that drive
exploration vs exploitation, enabling the agent to proactively discover and
prioritize optimization tasks without human prompting.
"""
from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass, field
from typing import Optional

from .observability import get_logger

logger = get_logger("intrinsic_motivation")


@dataclass
class MotivatedTask:
    """A task generated by the intrinsic motivation engine."""
    task_type: str  # profile / quality_check / optimize / explore / retrain
    description: str
    reward_estimate: float  # expected reward (0-100)
    urgency: float = 0.5  # 0-1 scale
    benefit: float = 0.5  # 0-1 scale
    priority_score: float = 0.0  # computed: urgency * benefit * reward
    source_discovery: Optional[dict] = None  # from DataLakeMonitor
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return {
            "task_type": self.task_type,
            "description": self.description,
            "reward_estimate": round(self.reward_estimate, 2),
            "urgency": round(self.urgency, 2),
            "benefit": round(self.benefit, 2),
            "priority_score": round(self.priority_score, 2),
            "source_discovery": self.source_discovery,
            "created_at": self.created_at,
        }


# ---------------------------------------------------------------------------
# Reward functions
# ---------------------------------------------------------------------------

REWARD_TABLE = {
    "new_data": 10.0,        # discovering new data source
    "data_drift": 8.0,       # detecting distribution change
    "perf_degradation": 7.0, # finding performance issue
    "optimization_opportunity": 5.0,  # finding optimization
    "quality_improvement": 5.0,  # improving data quality (per % improvement)
    "latency_reduction": 2.0,   # reducing latency (per second saved)
}


def compute_reward(discovery_type: str, metrics: dict = None) -> float:
    """Compute reward for a discovery based on type and impact metrics."""
    base = REWARD_TABLE.get(discovery_type, 1.0)
    multiplier = 1.0

    if metrics:
        # Scale by impact magnitude
        drift_pct = metrics.get("drift_pct", 0)
        if drift_pct > 50:
            multiplier = 2.0
        elif drift_pct > 20:
            multiplier = 1.5

        row_count = metrics.get("row_count", 0)
        if row_count > 100000:
            multiplier *= 1.3  # larger datasets = higher reward

    return base * multiplier


# ---------------------------------------------------------------------------
# Exploration strategy
# ---------------------------------------------------------------------------


class EpsilonGreedyStrategy:
    """ε-greedy strategy for balancing exploration vs exploitation.

    With probability ε, choose a random task (explore).
    With probability 1-ε, choose the highest-priority task (exploit).
    ε decays over time as the system learns.
    """

    def __init__(self, epsilon: float = 0.3, decay: float = 0.995, min_epsilon: float = 0.05):
        self.epsilon = epsilon
        self.decay = decay
        self.min_epsilon = min_epsilon
        self.step_count = 0

    def select(self, tasks: list[MotivatedTask]) -> Optional[MotivatedTask]:
        """Select a task using ε-greedy strategy."""
        if not tasks:
            return None

        self.step_count += 1
        current_epsilon = max(self.min_epsilon, self.epsilon * (self.decay ** self.step_count))

        if random.random() < current_epsilon:
            # Explore: random task
            selected = random.choice(tasks)
            logger.debug("ε-greedy: EXPLORE (ε=%.3f) → %s", current_epsilon, selected.task_type)
        else:
            # Exploit: highest priority
            selected = max(tasks, key=lambda t: t.priority_score)
            logger.debug("ε-greedy: EXPLOIT (ε=%.3f) → %s (score=%.2f)",
                        current_epsilon, selected.task_type, selected.priority_score)
        return selected

    @property
    def current_epsilon(self) -> float:
        return max(self.min_epsilon, self.epsilon * (self.decay ** self.step_count))


# ---------------------------------------------------------------------------
# Motivation Engine
# ---------------------------------------------------------------------------


class IntrinsicMotivationEngine:
    """Converts monitor discoveries into prioritized, motivated tasks.

    Pipeline: discoveries → reward estimation → priority scoring → ε-greedy selection
    """

    def __init__(self, epsilon: float = 0.3):
        self.strategy = EpsilonGreedyStrategy(epsilon=epsilon)
        self._task_history: list[MotivatedTask] = []

    def generate_tasks(self, discoveries: list[dict]) -> list[MotivatedTask]:
        """Convert monitor discoveries into motivated tasks with priority scores."""
        tasks = []
        for d in discoveries:
            dtype = d.get("discovery_type", "")
            metrics = d.get("metrics", {})
            reward = compute_reward(dtype, metrics)

            # Map discovery type to task type
            task_type_map = {
                "data_drift": "quality_check",
                "perf_degradation": "optimize",
                "optimization_opportunity": "optimize",
                "new_data": "profile",
            }
            task_type = task_type_map.get(dtype, "explore")

            # Compute urgency from severity
            severity_map = {"critical": 1.0, "warning": 0.7, "info": 0.3}
            urgency = severity_map.get(d.get("severity", "info"), 0.3)

            # Benefit = reward normalized to 0-1
            benefit = min(1.0, reward / 20.0)

            # Priority = urgency × benefit × log(reward + 1)
            priority = urgency * benefit * math.log(reward + 1)

            task = MotivatedTask(
                task_type=task_type,
                description=d.get("suggested_action", d.get("title", "")),
                reward_estimate=reward,
                urgency=urgency,
                benefit=benefit,
                priority_score=priority,
                source_discovery=d,
            )
            tasks.append(task)

        # Sort by priority descending
        tasks.sort(key=lambda t: t.priority_score, reverse=True)
        return tasks

    def select_next_task(self, discoveries: list[dict]) -> Optional[dict]:
        """Generate tasks from discoveries and select the next one to execute.

        Uses ε-greedy strategy for exploration/exploitation balance.
        """
        tasks = self.generate_tasks(discoveries)
        if not tasks:
            return None

        selected = self.strategy.select(tasks)
        if selected:
            self._task_history.append(selected)
            return selected.to_dict()
        return None

    def get_task_history(self, limit: int = 20) -> list[dict]:
        """Get history of selected tasks."""
        return [t.to_dict() for t in self._task_history[-limit:]]

    @property
    def stats(self) -> dict:
        return {
            "total_tasks_generated": len(self._task_history),
            "epsilon": round(self.strategy.current_epsilon, 4),
            "step_count": self.strategy.step_count,
        }


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

_engine: Optional[IntrinsicMotivationEngine] = None


def get_motivation_engine() -> IntrinsicMotivationEngine:
    global _engine
    if _engine is None:
        _engine = IntrinsicMotivationEngine()
    return _engine


def reset_motivation_engine():
    global _engine
    _engine = None
