"""Deterministic KG hints for major-project NL2Semantic2SQL queries.

The resolver projects common major-project graph concepts onto the Postgres
tables generated by the synthetic major-project artifacts. It does not connect
to Neo4j or any database at runtime.
"""
from __future__ import annotations

from typing import Any


GRAPH_BACKEND = "postgres_projection"
PROJECT_ENTITY = "重大项目"
PROJECT_TABLE = "mp_project_list"
DEFAULT_SPATIAL_OVERLAP_THRESHOLD = 0.3

KNOWN_MAJOR_PROJECT_TABLES = {
    PROJECT_TABLE,
    "mp_pre_review",
    "mp_conversion_expropriation",
    "mp_land_supply",
    "mp_parcel",
    "mp_relation_confidence",
}

PROJECT_JOIN_PATHS = {
    "mp_pre_review": "mp_project_list.project_id -> mp_pre_review.project_id",
    "mp_conversion_expropriation": (
        "mp_project_list.project_id -> mp_conversion_expropriation.project_id"
    ),
    "mp_land_supply": "mp_project_list.project_id -> mp_land_supply.project_id",
    "mp_parcel": "mp_project_list.project_id -> mp_parcel.project_id",
}

RELATION_CONFIDENCE_PARCEL_JOIN = (
    "mp_relation_confidence.target_id -> mp_parcel.parcel_id"
)

MAJOR_PROJECT_DOMAIN_TOKENS = (
    "审批流程",
    "流程断点",
    "断点",
    "用地预审",
    "预审",
    "农转征",
    "农转用",
    "农用地转用",
    "土地征收",
    "供地",
    "土地供应",
    "空间叠加",
    "叠加补全",
    "补全关联",
    "major_project",
    "mp_project",
)


def resolve_major_project_kg_hints(
    question: str,
    semantic: dict | None = None,
    intent: str | None = None,
) -> dict[str, Any]:
    """Resolve major-project KG hints from a natural-language question.

    The output is intentionally small, ordered, and deterministic so downstream
    NL2Semantic2SQL code can merge it into grounding without runtime services.
    """
    question_text = question or ""
    hint_text = _semantic_hint_text(semantic)
    combined_text = " ".join(
        part for part in (question_text, intent or "", hint_text) if part
    )
    combined_low = combined_text.lower()

    result: dict[str, Any] = {
        "matched_entities": [],
        "lifecycle_stage": None,
        "required_edges": [],
        "missing_stage_filter": False,
        "spatial_overlap_threshold": None,
        "candidate_tables": [],
        "join_paths": [],
        "graph_backend": GRAPH_BACKEND,
    }

    if _looks_like_major_project_question(combined_text, combined_low):
        _add_unique(result["matched_entities"], PROJECT_ENTITY)
        _add_unique(result["candidate_tables"], PROJECT_TABLE)

    semantic_tables = _semantic_candidate_tables(semantic)
    if semantic_tables:
        _add_unique(result["candidate_tables"], PROJECT_TABLE)
    for table_name in semantic_tables:
        _add_unique(result["candidate_tables"], table_name)

    if _mentions_missing_stage(combined_text, combined_low):
        result["missing_stage_filter"] = True
        _add_unique(result["matched_entities"], PROJECT_ENTITY)
        _add_unique(result["required_edges"], "MISSING_STAGE")
        _add_unique(result["candidate_tables"], PROJECT_TABLE)

    mentions_pre_review = _contains_any(
        combined_text,
        "用地预审",
        "预审",
        "pre_review",
        "HAS_PRE_REVIEW",
    )
    mentions_conversion = _contains_any(
        combined_text,
        "农转征",
        "农转用",
        "农用地转用",
        "土地征收",
        "conversion_expropriation",
        "HAS_CONVERSION",
    )
    if mentions_pre_review:
        _add_unique(result["matched_entities"], PROJECT_ENTITY)
        _add_unique(result["required_edges"], "HAS_PRE_REVIEW")
        _add_unique(result["candidate_tables"], PROJECT_TABLE)
        _add_unique(result["candidate_tables"], "mp_pre_review")
    if mentions_conversion:
        _add_unique(result["matched_entities"], PROJECT_ENTITY)
        _add_unique(result["required_edges"], "HAS_CONVERSION")
        _add_unique(result["candidate_tables"], PROJECT_TABLE)
        _add_unique(result["candidate_tables"], "mp_conversion_expropriation")
    if (
        mentions_pre_review
        and mentions_conversion
        and _contains_any(
            combined_text,
            "未完成",
            "未办理",
            "未办结",
            "没有",
            "缺少",
            "无",
            "without",
        )
    ):
        result["lifecycle_stage"] = "pre_review_without_conversion"

    if _contains_any(
        combined_text,
        "供地",
        "土地供应",
        "land supply",
        "mp_land_supply",
        "HAS_LAND_SUPPLY",
    ):
        _add_unique(result["matched_entities"], PROJECT_ENTITY)
        _add_unique(result["required_edges"], "HAS_LAND_SUPPLY")
        _add_unique(result["candidate_tables"], PROJECT_TABLE)
        _add_unique(result["candidate_tables"], "mp_land_supply")

    if _mentions_spatial_overlay(combined_text, combined_low):
        result["spatial_overlap_threshold"] = DEFAULT_SPATIAL_OVERLAP_THRESHOLD
        _add_unique(result["matched_entities"], PROJECT_ENTITY)
        _add_unique(result["required_edges"], "OCCUPIES_PARCEL")
        _add_unique(result["required_edges"], "SPATIALLY_OVERLAPS")
        _add_unique(result["candidate_tables"], PROJECT_TABLE)
        _add_unique(result["candidate_tables"], "mp_relation_confidence")
        _add_unique(result["candidate_tables"], "mp_parcel")

    _populate_join_paths(result["candidate_tables"], result["join_paths"])
    return result


def _looks_like_major_project_question(text: str, text_low: str) -> bool:
    if _contains_any(text, PROJECT_ENTITY, "重点项目", "major project", "major_project"):
        return True
    return "项目" in text and any(
        token in text or token.lower() in text_low
        for token in MAJOR_PROJECT_DOMAIN_TOKENS
    )


def _mentions_missing_stage(text: str, text_low: str) -> bool:
    if _contains_any(text, "流程断点", "审批流程断点", "断点", "MISSING_STAGE"):
        return True
    stage_words = ("阶段", "环节", "流程", "stage")
    missing_words = ("缺失", "缺少", "遗漏", "漏办", "missing")
    return (
        any(token in text or token in text_low for token in stage_words)
        and any(token in text or token in text_low for token in missing_words)
    )


def _mentions_spatial_overlay(text: str, text_low: str) -> bool:
    return _contains_any(
        text,
        "空间叠加",
        "叠加补全",
        "补全关联",
        "空间覆盖",
        "空间关联",
        "spatial overlay",
        "spatially_overlaps",
        "OCCUPIES_PARCEL",
        "SPATIALLY_OVERLAPS",
    ) or ("spatial" in text_low and "overlap" in text_low)


def _populate_join_paths(candidate_tables: list[str], join_paths: list[str]) -> None:
    tables = set(candidate_tables)
    if PROJECT_TABLE in tables:
        for table_name, join_path in PROJECT_JOIN_PATHS.items():
            if table_name in tables:
                _add_unique(join_paths, join_path)
    if {"mp_relation_confidence", "mp_parcel"} <= tables:
        _add_unique(join_paths, RELATION_CONFIDENCE_PARCEL_JOIN)


def _semantic_hint_text(semantic: dict | None) -> str:
    if not isinstance(semantic, dict):
        return ""

    parts: list[str] = []
    for key in ("intent", "domain", "query_type", "lifecycle_stage"):
        value = semantic.get(key)
        if value:
            parts.append(str(value))

    for key in ("matched_entities", "required_edges", "candidate_tables"):
        value = semantic.get(key)
        if isinstance(value, list):
            for item in value:
                if isinstance(item, str):
                    parts.append(item)
                elif isinstance(item, dict):
                    name = (
                        item.get("table_name")
                        or item.get("name")
                        or item.get("edge_type")
                    )
                    if name:
                        parts.append(str(name))
    return " ".join(parts)


def _semantic_candidate_tables(semantic: dict | None) -> list[str]:
    if not isinstance(semantic, dict):
        return []

    tables: list[str] = []
    for item in semantic.get("candidate_tables", []) or []:
        table_name = item.get("table_name") if isinstance(item, dict) else item
        if isinstance(table_name, str) and table_name in KNOWN_MAJOR_PROJECT_TABLES:
            _add_unique(tables, str(table_name))
    return tables


def _contains_any(text: str, *tokens: str) -> bool:
    text_low = text.lower()
    return any(token in text or token.lower() in text_low for token in tokens)


def _add_unique(items: list[str], value: str) -> None:
    if value not in items:
        items.append(value)


__all__ = ["resolve_major_project_kg_hints"]
