from __future__ import annotations
import hashlib,json
from copy import deepcopy
CHANNELS=('iot_sensor_inventory','camera_inventory_and_online_state','smart_lighting_assets','public_wifi_assets','mobile_network_base_stations','edge_and_data_center_assets','smart_parking_devices','environment_monitoring_terminals','urban_operations_center_integrations','device_fault_and_maintenance_history','network_service_availability','service_usage_and_request_timeseries')
REQUIRED=['asset_id','asset_type','operator_or_owner_reference','longitude','latitude','admin_unit_id','installation_or_commission_date','operational_status','status_observed_at','source_system','source_record_id','quality_status']
def build_digital_readiness_product(*,platform_capabilities,source_artifacts):
 caps=deepcopy(platform_capabilities)
 for x in caps:
  if x.get('status')=='verified' and not x.get('evidence_artifacts'):raise ValueError('verified_capability_evidence_missing')
 channels={k:{'status':'unavailable','value':None,'required_fields':REQUIRED,'required_spatial_grain':'asset_point_with_explicit_admin_unit_id','required_temporal_grain':'current_state_and_event_history','authoritative_source_requirement':'operator_or_government_asset_registry','quality_requirements':['stable_asset_id','timestamped_status','source_lineage','coordinate_validation'],'production_blockers':['authoritative_asset_inventory_missing','operational_timeseries_missing']} for k in CHANNELS}
 gate={'status':'closed','mechanisms':{'asset_state_transition':'closed','failure_propagation':'closed','maintenance_response':'closed','service_recovery':'closed','counterfactual_maintenance':'closed'},'required_evidence':['digital_asset_state','failure_event','maintenance_action','service_dependency_graph','service_interruption_propagation','recovery_transition','usage_demand_state','held_out_failure_and_recovery_evaluation']}
 digest={'caps':caps,'channels':channels};bid='digital-readiness-'+hashlib.sha256(json.dumps(digest,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()[:20]
 return {'schema':'uwm.digital_asset_smart_district_readiness.v1','bundle_id':bid,'views':{'platform_digital_capability':{},'smart_district_infrastructure_readiness':{}},'summary':{'platform_capability_count':len(caps),'verified_platform_capability_count':sum(x.get('status')=='verified' for x in caps),'infrastructure_channel_count':len(channels),'available_infrastructure_channel_count':0},'platform_capabilities':caps,'infrastructure_channels':channels,'data_contracts':{'smart_infrastructure_asset':{'required_fields':REQUIRED},'operational_history':{'required_fields':['asset_id','event_type','started_at','ended_at','observed_status','maintenance_action','source_system']}},'uwm_gate':gate,'source_artifacts':sorted(map(str,source_artifacts)),'claim_boundary':{'max_claim_level':'platform_digital_capability_and_district_smart_infrastructure_evidence_readiness','platform_capability_not_district_infrastructure_coverage':True,'registered_api_not_observed_service_use':True,'asset_presence_not_operational_availability':True,'poi_or_facility_not_iot_asset':True,'missing_inventory_not_zero_coverage':True,'readiness_not_digital_maturity':True,'closed_digital_uwm_gate_not_failure_prediction':True},'fabricated_value_count':0}
