from __future__ import annotations
import hashlib,json
from copy import deepcopy
CHANNELS=('approved_service_catalog','contractual_sla_definitions','service_availability_observations','incident_records','problem_records','change_records','customer_tickets','response_and_recovery_timestamps','responsible_team_and_escalation','asset_lifecycle_records','root_cause_and_corrective_actions','customer_satisfaction','maintenance_costs','external_service_benchmarks')
def build_operations_quality_product(*,platform_operations,source_artifacts):
 caps=deepcopy(platform_operations)
 for x in caps:
  if not x.get('evidence_paths'):raise ValueError('platform_operation_evidence_missing')
 channels={k:{'status':'unavailable','value':None,'production_blockers':['authoritative_customer_operations_source_missing']} for k in CHANNELS}
 contracts={'sla_definition':{'required_fields':['sla_id','service_id','customer_scope','measurement_window','timezone','availability_target','response_target','recovery_target','priority_rules','exclusions','approved_version','effective_from','effective_to','source_system']},'incident_ticket':{'required_fields':['record_id','record_type','service_id','priority','opened_at','acknowledged_at','resolved_at','closed_at','status','customer_scope','responsible_team','escalation_level','root_cause','corrective_action','source_system','source_record_id']}}
 gate={'status':'closed','mechanisms':{'failure_propagation':'closed','recovery_time_prediction':'closed','recurrence_risk':'closed','maintenance_effect':'closed','sla_breach_prediction':'closed','resource_dispatch_optimization':'closed'},'required_evidence':['service_state','incident_event','maintenance_action','service_dependency_graph','failure_propagation','recovery_transition','recurrence_state','counterfactual_maintenance','held_out_incident_recovery_evaluation']}
 digest={'caps':caps,'channels':channels};bid='operations-quality-'+hashlib.sha256(json.dumps(digest,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()[:20]
 return {'schema':'uwm.operations_service_quality_readiness.v1','bundle_id':bid,'views':{'platform_operations_evidence':{},'customer_sla_ticket_readiness':{},'operations_uwm_readiness':{}},'summary':{'platform_operation_capability_count':len(caps),'customer_channel_count':len(channels),'available_customer_channel_count':0,'open_uwm_mechanism_count':0},'platform_operations':caps,'customer_channels':channels,'data_contracts':contracts,'uwm_gate':gate,'source_artifacts':sorted(map(str,source_artifacts)),'claim_boundary':{'max_claim_level':'platform_operations_evidence_and_customer_service_management_readiness','internal_threshold_not_customer_contract_sla':True,'platform_metrics_not_customer_service_quality':True,'alert_not_confirmed_incident':True,'workflow_failure_not_asset_failure':True,'missing_ticket_data_not_zero_incidents':True,'observability_not_root_cause':True,'source_code_capability_not_observed_operation':True},'fabricated_value_count':0}
