from __future__ import annotations
import hashlib,json
from copy import deepcopy
GATES=('hazard_evidence_gate','exposure_evidence_gate','response_capacity_evidence_gate','propagation_evidence_gate','recovery_evidence_gate','intervention_evidence_gate','evaluation_evidence_gate')
BLOCKERS={'hazard_evidence_gate':['authoritative_hazard_event_timeseries_missing'],'exposure_evidence_gate':['population_and_asset_exposure_missing','observed_damage_state_missing'],'response_capacity_evidence_gate':['emergency_response_time_missing','response_capacity_observations_missing'],'propagation_evidence_gate':['hazard_spatial_propagation_calibration_missing'],'recovery_evidence_gate':['recovery_state_timeseries_missing','recovery_transition_calibration_missing'],'intervention_evidence_gate':['resilience_intervention_registry_missing','intervention_outcome_evidence_missing'],'evaluation_evidence_gate':['held_out_event_evaluation_missing']}
def validate_resilience_graph(edges):
 for x in edges:
  if not x.get('edge_provenance'):raise ValueError('edge_provenance_required')
  if x.get('propagation_parameter') is not None:raise ValueError('propagation_parameter_must_be_null')
 return True
def build_resilience_kernel_product(*,nodes,edges,dependency_chain,source_artifacts):
 validate_resilience_graph(edges);state=[]
 for raw in nodes:
  x=deepcopy(raw);x.update({'spatial_grain':x.get('spatial_grain') or 'administrative_context','evidence_coverage':x.get('evidence_coverage') or {},'limitations':{'network_context_not_hazard_propagation':True,'facility_presence_not_response_capacity':True,'evidence_gap_not_resilience_risk':True}});state.append(x)
 gates={g:{'status':'observed_context' if g in {'response_capacity_evidence_gate'} else 'closed','support_level':'context_only' if g=='response_capacity_evidence_gate' else 'unavailable','source_ids':sorted(map(str,source_artifacts)) if g=='response_capacity_evidence_gate' else [],'required_evidence':BLOCKERS[g],'blockers':BLOCKERS[g],'max_supported_claim':'observed_facility_context_only' if g=='response_capacity_evidence_gate' else 'mechanism_closed'} for g in GATES}
 rollout={'disturbance_transition_status':'closed','hazard_propagation_status':'closed','response_capacity_status':'closed','recovery_transition_status':'closed','intervention_effect_status':'closed','counterfactual_status':'closed','baseline_observed_state_count':len(state),'future_trajectory':None,'disturbance':None,'action':None,'uncertainty':None,'blockers':sorted({b for v in BLOCKERS.values() for b in v}),'limitations':{'closed_rollout_not_failed_simulation':True,'adjacency_not_transmission_coefficient':True,'environment_temporal_dynamics_not_disaster_recovery':True}}
 digest={'state':state,'graph':edges,'dependencies':dependency_chain};bid='resilience-kernel-'+hashlib.sha256(json.dumps(digest,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()[:20]
 return {'schema':'uwm.resilience_kernel_foundation.v1','bundle_id':bid,'summary':{'state_node_count':len(state),'graph_edge_count':len(edges),'evidence_gate_count':len(gates),'open_transition_mechanism_count':0},'state':state,'graph':deepcopy(edges),'evidence_gates':gates,'current_rollout':rollout,'dependency_chain':list(dependency_chain),'source_artifacts':sorted(map(str,source_artifacts)),'claim_boundary':{'max_claim_level':'observed_resilience_context_spatial_graph_and_fail_closed_kernel_readiness','network_context_not_hazard_propagation':True,'facility_presence_not_response_capacity':True,'adjacency_not_transmission_coefficient':True,'environment_temporal_dynamics_not_disaster_recovery':True,'closed_rollout_not_failed_simulation':True,'evidence_gap_not_resilience_risk':True,'dependency_task_not_intervention_recommendation':True},'fabricated_value_count':0}
