"""Synthetic policy-outcome scaffold for UWM offline policy evaluation gates."""

from __future__ import annotations

from typing import Any

from .contracts import UWM_OBSERVATION_SCHEMA
from .simulator import simulate_livability_rollout


SYNTHETIC_POLICY_OUTCOME_BENCHMARK_SCHEMA = "uwm.synthetic_policy_outcome_benchmark.v1"
DEFAULT_SYNTHETIC_POLICY_OUTCOME_BACKEND = "simulator_replay_policy_outcome_scaffold_v0"


def build_synthetic_policy_outcome_benchmark(
    search_report: dict[str, Any],
    learned_rollout_report: dict[str, Any],
    *,
    benchmark_id: str,
    created_at: str,
    scenario: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a clearly synthetic policy-outcome comparison scaffold.

    The benchmark is useful for OPE wiring and negative controls only. It must
    not be interpreted as observed intervention evidence.
    """

    graph_state = search_report.get("graph_mdp_state") or {}
    if not graph_state.get("nodes"):
        raise ValueError("synthetic policy outcome benchmark requires graph_mdp_state nodes")

    scenario = scenario or _scenario_from_search_report(search_report)
    observation = _observation_from_graph_state(
        graph_state,
        observation_id=f"{benchmark_id}-synthetic-observation",
        created_at=created_at,
    )
    policies = _policy_candidates(search_report, learned_rollout_report)
    outcomes = [
        _simulate_policy_outcome(policy, observation=observation, scenario=scenario)
        for policy in policies
        if policy["action_sequence"]
    ]
    by_policy = {row["policy_id"]: row for row in outcomes}
    static_reward = _reward_for_policy(by_policy, "static_single_step_heuristic")
    graph_reward = _reward_for_policy(by_policy, "graph_mdp_known_effect_best")
    learned_reward = _reward_for_policy(by_policy, "learned_world_model_rollout")
    return {
        "schema": SYNTHETIC_POLICY_OUTCOME_BENCHMARK_SCHEMA,
        "benchmark_id": benchmark_id,
        "created_at": created_at,
        "backend": DEFAULT_SYNTHETIC_POLICY_OUTCOME_BACKEND,
        "source_report_schema": search_report.get("schema"),
        "source_learned_rollout_schema": learned_rollout_report.get("schema"),
        "synthetic_status": "synthetic",
        "quality_status": "synthetic_policy_outcome_not_observed",
        "scenario": scenario,
        "synthetic_policy_outcomes": outcomes,
        "comparisons": {
            "graph_search_advantage_over_static": round(graph_reward - static_reward, 9),
            "learned_rollout_advantage_over_static": round(learned_reward - static_reward, 9),
            "learned_rollout_advantage_over_graph_search": round(learned_reward - graph_reward, 9),
        },
        "supported_claim": (
            "synthetic_policy_outcome_scaffold_ready"
            if outcomes and learned_reward > static_reward
            else "synthetic_policy_outcome_scaffold_no_advantage"
        ),
        "empirical_superiority_claim": False,
        "claim_boundary": {
            "max_claim_level": "exploratory_only",
            "reason": "policy outcomes are generated by the UWM simulator, not observed intervention data",
        },
        "remaining_gates": [
            "observed_policy_outcome_required",
            "off_policy_evaluation_on_observed_or_quasi_observed_data_required",
            "causal_policy_effect_validation_required",
            "external_air_pollution_holdout_required",
        ],
        "synthetic_generation_trace": [
            {
                "step": "reconstruct_canonical_observation_from_graph_mdp_state",
                "node_count": len(graph_state.get("nodes") or []),
                "edge_count": len(graph_state.get("edges") or []),
            },
            {
                "step": "simulate_policy_sequences_with_same_scenario",
                "policy_count": len(outcomes),
                "backend": DEFAULT_SYNTHETIC_POLICY_OUTCOME_BACKEND,
            },
            {
                "step": "preserve_claim_boundary",
                "empirical_superiority_claim": False,
                "synthetic_status": "synthetic",
            },
        ],
    }


def _policy_candidates(
    search_report: dict[str, Any],
    learned_rollout_report: dict[str, Any],
) -> list[dict[str, Any]]:
    static_actions = [
        _normalise_static_action(action)
        for action in (search_report.get("static_single_step_baseline") or {}).get("action_sequence") or []
    ]
    best_actions = list((search_report.get("best_sequence") or {}).get("action_sequence") or [])
    learned_actions = list(
        (
            (learned_rollout_report.get("learned_rollout_planner") or {}).get("selected_sequence")
            or {}
        ).get("action_sequence")
        or []
    )
    return [
        {
            "policy_id": "static_single_step_heuristic",
            "policy_class": "traditional_static_baseline",
            "action_sequence": static_actions,
        },
        {
            "policy_id": "graph_mdp_known_effect_best",
            "policy_class": "known_effect_graph_search",
            "action_sequence": best_actions,
        },
        {
            "policy_id": "learned_world_model_rollout",
            "policy_class": "learned_world_model_imagined_rollout",
            "action_sequence": learned_actions,
        },
    ]


def _simulate_policy_outcome(
    policy: dict[str, Any],
    *,
    observation: dict[str, Any],
    scenario: dict[str, Any],
) -> dict[str, Any]:
    rollout = simulate_livability_rollout(
        observation,
        list(policy["action_sequence"]),
        scenario=scenario,
    )
    reward = _synthetic_reward(rollout)
    return {
        "policy_id": policy["policy_id"],
        "policy_class": policy["policy_class"],
        "synthetic_status": "synthetic",
        "quality_status": "synthetic_policy_outcome_not_observed",
        "action_count": len(policy["action_sequence"]),
        "action_sequence": policy["action_sequence"],
        "synthetic_reward": round(reward, 9),
        "outcome_components": {
            "heat_risk_delta": round(_float(rollout.get("heat_risk_delta")), 9),
            "air_pollution_exposure_delta": round(_float(rollout.get("air_pollution_exposure_delta")), 9),
            "service_accessibility_delta": round(_float(rollout.get("service_accessibility_delta")), 9),
            "equity_delta": round(_float(rollout.get("equity_delta")), 9),
            "livability_delta": round(_float(rollout.get("livability_delta")), 9),
        },
        "evidence_grade": rollout.get("evidence_grade"),
        "claim_boundary": rollout.get("claim_boundary"),
    }


def _observation_from_graph_state(
    graph_state: dict[str, Any],
    *,
    observation_id: str,
    created_at: str,
) -> dict[str, Any]:
    return {
        "schema": UWM_OBSERVATION_SCHEMA,
        "observation_id": observation_id,
        "created_at": created_at,
        "spatial_units": [
            {
                "unit_id": str(node.get("unit_id") or node.get("node_id")),
                "unit_type": str(node.get("node_type") or "graph_mdp_unit"),
                **{
                    key: _float((node.get("features") or {}).get(key))
                    for key in [
                        "heat_risk",
                        "air_pollution_exposure",
                        "service_accessibility",
                        "equity",
                        "livability",
                    ]
                },
            }
            for node in graph_state.get("nodes") or []
            if node.get("unit_id") is not None or node.get("node_id") is not None
        ],
        "object_layers": [
            {
                "role": "synthetic_policy_outcome_reconstructed_graph_state",
                "source_dataset_id": graph_state.get("state_id"),
            }
        ],
        "raster_features": [],
        "graph_edges": [
            {
                "source": str(edge.get("source")),
                "target": str(edge.get("target")),
                "edge_type": str(edge.get("edge_type") or "graph_mdp_adjacency"),
                "weight": _float(edge.get("weight"), default=1.0),
            }
            for edge in graph_state.get("edges") or []
            if edge.get("source") is not None and edge.get("target") is not None
        ],
        "temporal_index": {
            "observation_created_at": created_at,
            "source_graph_state_id": graph_state.get("state_id"),
        },
        "quality_flags": [
            {
                "level": "warning",
                "message": "synthetic policy outcome scaffold reconstructed from Graph-MDP state",
            }
        ],
        "synthetic_flags": [
            {
                "dataset_id": "synthetic_policy_outcome_scaffold",
                "status": "synthetic",
            }
        ],
        "provenance": {
            "source_graph_state_id": graph_state.get("state_id"),
            "source_state_encoder": graph_state.get("state_encoder"),
        },
        "claim_boundary": {
            "max_claim_level": "exploratory_only",
            "reason": "synthetic policy outcome scaffold uses simulator-generated outcomes",
        },
        "renderer_trace": [
            {
                "step": "reconstruct_from_graph_mdp_state_for_synthetic_policy_outcome",
                "state_id": graph_state.get("state_id"),
            }
        ],
    }


def _scenario_from_search_report(search_report: dict[str, Any]) -> dict[str, Any]:
    rollout_trace = (search_report.get("best_sequence") or {}).get("rollout_trace") or {}
    scenario = rollout_trace.get("scenario")
    if isinstance(scenario, dict) and scenario:
        return dict(scenario)
    return {
        "scenario_id": "synthetic_policy_outcome_scaffold",
        "heat_stress_multiplier": 1.0,
        "air_pollution_stress_multiplier": 1.0,
        "vulnerability_multiplier": 1.0,
    }


def _synthetic_reward(rollout: dict[str, Any]) -> float:
    interval = rollout.get("uncertainty_interval") or {}
    uncertainty_width = _float(interval.get("high")) - _float(interval.get("low"))
    return (
        _float(rollout.get("livability_delta"))
        + 0.50 * _float(rollout.get("equity_delta"))
        - 0.10 * uncertainty_width
    )


def _normalise_static_action(action: dict[str, Any]) -> dict[str, Any]:
    normalised = dict(action)
    action_id = str(normalised.get("action_id") or "")
    if action_id.startswith("static-"):
        normalised["action_id"] = action_id.removeprefix("static-")
    return normalised


def _reward_for_policy(rows: dict[str, dict[str, Any]], policy_id: str) -> float:
    return _float((rows.get(policy_id) or {}).get("synthetic_reward"))


def _float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default
