"""Self-contained private review page for completed spatial screenings."""
from __future__ import annotations
import json


def render_review_page(results: list[dict]) -> str:
    if not results:
        raise ValueError("pond_review_results_required")
    payload = json.dumps(results, ensure_ascii=False, allow_nan=False).replace("<", "\\u003c")
    return '''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>阿布扎比调蓄方案 · 真实试点空间筛选</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f5f7;color:#21364a;font:14px/1.6 system-ui,"Heiti SC",sans-serif}main{max-width:1400px;margin:auto;padding:28px}h1{font-size:26px;margin:5px 0}p{max-width:1050px}.kicker{color:#567082;font-size:12px;letter-spacing:.12em}.controls,.metrics{display:flex;gap:14px;flex-wrap:wrap;margin:18px 0}select,button{padding:9px 14px;border:1px solid #b4c7d3;border-radius:6px;background:white;color:inherit;font:inherit}.metrics span{padding:12px 18px;background:white;border-radius:8px}.metrics b{font-size:25px;margin-left:15px}.grid{display:grid;grid-template-columns:1.25fr 1fr;gap:20px}.card{background:#fff;border:1px solid #d6e1e8;border-radius:10px;padding:18px;min-width:0}svg{width:100%;height:580px;background:#f8fbfc;border-radius:8px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:9px 6px;text-align:left;border-bottom:1px solid #e4eaee}tr.selected{background:#fef1d5}.scroll{max-height:580px;overflow:auto}td button{font-size:12px;padding:3px 8px}a{color:#166785}.note{color:#647887;font-size:12px}#details{padding:12px;background:#f3f7f9;margin-top:12px;min-height:65px}.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:12px;margin-bottom:12px}label{cursor:pointer}input{accent-color:#2b7889}footer{font-size:12px;margin-top:18px;color:#647887}.tag{padding:5px 10px;border-radius:5px;background:#fff0d4;color:#926310;white-space:nowrap}@media(max-width:850px){.grid{grid-template-columns:1fr}main{padding:16px}svg{height:450px}}
</style><main><div class="kicker">ABU DHABI · POND PLANNING</div><h1>调蓄方案：真实试点空间筛选</h1>
<p>筛选附近地块和现状塘，识别勘测连接及设施冲突。候选均待核验；连接线表示距离下界，可用库容、重力可达性、排空能力和成本仍需工程数据支持。</p>
<div class="controls"><select id="pilot" aria-label="选择试点"></select><span class="tag">空间初筛 · 尚未运行水力或成本优化</span></div>
<div class="metrics" id="metrics"></div><div class="grid"><div class="card"><div class="legend">
<label><input type="checkbox" checked data-layer="candidates"> 🟠 候选地块/塘</label><label><input type="checkbox" checked data-layer="connections"> 勘测连接</label><label><input type="checkbox" checked data-layer="existing_ponds"> 🔵 现状塘参考</label><label><input type="checkbox" checked data-layer="hotspots"> 🔴 热点</label></div>
<svg id="map" viewBox="0 0 700 580" aria-label="候选位置示意图"></svg><p class="note">位置示意图，无外部底图请求。面积和距离由 EPSG:32640 米制坐标计算。点击右侧编号高亮对应候选；现状塘参考可能位于汇水区外。</p></div>
<div class="card"><div class="scroll"><table><thead><tr><th>来源编号</th><th>类型</th><th>面积 m²</th><th>最近距离 m</th><th>设施重叠数</th></tr></thead><tbody id="rows"></tbody></table></div><div id="details">点击编号查看候选。</div></div></div>
<div class="card" style="margin-top:18px"><b>当前规则与核验重点</b><p id="policy"></p><p>地块或走廊存在不等于允许开挖。设施重叠数来自已接入图层及暂定缓冲；零重叠不代表地下设施清障完成。下一步应核验土地和排水许可、入口—路线—塘—出口高程、塘形曲线、地下水、泵管性能、雨潮过程及分项单价。</p><div id="exports" class="controls"></div></div><footer id="version"></footer></main>
<script type="application/json" id="data">''' + payload + '''</script><script>
const results=JSON.parse(document.getElementById('data').textContent), ns='http://www.w3.org/2000/svg', pilot=document.getElementById('pilot');
results.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.catchment.label+' · #'+r.catchment_fid;pilot.append(o)});
const number=v=>v===null||v===undefined?'待核':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:2});
function coords(g){const a=[];function walk(c){if(typeof c[0]==='number')a.push(c);else c.forEach(walk)}walk(g.coordinates);return a}
function choose(id){document.querySelectorAll('[data-candidate]').forEach(e=>{const same=e.dataset.candidate===id;e.style.opacity=same?'1':'.18';if(e.tagName.toLowerCase()==='tr')e.classList.toggle('selected',same)});const r=results[+pilot.value],c=r.candidates.find(x=>x.candidate_id===id);document.getElementById('details').textContent=c?c.candidate_id+'；许可未核实；可用库容待核；成本待核。':'请选择候选';}
function draw(){const r=results[+pilot.value], svg=document.getElementById('map');svg.replaceChildren();document.getElementById('rows').replaceChildren();document.getElementById('details').textContent='点击编号查看候选。';
document.getElementById('metrics').replaceChildren();for(const [label,k] of [['热点','hotspots'],['待核候选','selected_candidates'],['勘测连接','connections'],['附近现状塘','existing_pond_references']]){const s=document.createElement('span');s.append(label);const b=document.createElement('b');b.textContent=r.summary[k];s.append(b);document.getElementById('metrics').append(s)}
const all=Object.values(r.geojson).flatMap(fc=>fc.features.flatMap(f=>coords(f.geometry))), xs=all.map(p=>p[0]),ys=all.map(p=>p[1]);const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),cos=Math.cos((ymin+ymax)/2*Math.PI/180),scale=Math.min(650/((xmax-xmin)*cos),530/(ymax-ymin));const xy=p=>[25+(p[0]-xmin)*cos*scale,555-(p[1]-ymin)*scale];
function path(g){let lines=[],close=false;if(g.type==='Polygon'){lines=g.coordinates;close=true}else if(g.type==='MultiPolygon'){lines=g.coordinates.flat();close=true}else if(g.type==='LineString')lines=[g.coordinates];else if(g.type==='MultiLineString')lines=g.coordinates;return lines.map(l=>l.map((p,i)=>(i?'L':'M')+xy(p).join(',')).join(' ')+(close?' Z':'')).join(' ')}
for(const [key,color,fill] of [['catchment','#687f90','#e5edf150'],['existing_ponds','#2c8ec1','#389bc850'],['candidates','#c38a20','#ebbc6060'],['connections','#c86645','none'],['hotspots','#c63450','#c63450']]){const group=document.createElementNS(ns,'g');group.dataset.layer=key;svg.append(group);for(const f of r.geojson[key].features){let e;if(f.geometry.type==='Point'){e=document.createElementNS(ns,'circle');const [x,y]=xy(f.geometry.coordinates);e.setAttribute('cx',x);e.setAttribute('cy',y);e.setAttribute('r',4)}else{e=document.createElementNS(ns,'path');e.setAttribute('d',path(f.geometry));e.setAttribute('fill-rule','evenodd')}e.setAttribute('stroke',color);e.setAttribute('fill',fill);e.setAttribute('stroke-width',key==='catchment'?1.1:1.7);if(key==='connections')e.setAttribute('stroke-dasharray','5 3');if(f.properties.candidate_id){e.dataset.candidate=f.properties.candidate_id;e.addEventListener('click',()=>choose(f.properties.candidate_id))}const title=document.createElementNS(ns,'title');title.textContent=f.properties.candidate_id||f.properties.source_key||r.catchment.label;e.append(title);group.append(e)}}
for(const c of r.candidates){const row=document.createElement('tr');row.dataset.candidate=c.candidate_id;const first=document.createElement('td'),button=document.createElement('button');button.textContent=c.source_fid;button.addEventListener('click',()=>choose(c.candidate_id));first.append(button);row.append(first);for(const v of [c.kind==='parcel'?'地块待核':'现状塘',number(c.screening_area_m2),number(c.minimum_distance_m),number(c.utility_overlap_count)]){const td=document.createElement('td');td.textContent=v;row.append(td)}document.getElementById('rows').append(row)}
document.getElementById('policy').textContent='最大距离 '+r.policy.maximum_distance_m+' 米；最小面积 '+r.policy.minimum_area_m2+' 平方米；暂定退界 '+r.policy.setback_m+' 米；设施缓冲 '+r.policy.utility_buffer_m+' 米；每个热点取最近 '+r.policy.alternatives_per_hotspot+' 个空间候选。';
document.getElementById('version').textContent='数据版本：'+r.snapshot_id+' ｜ 筛选编号：'+r.screening_id+' ｜ 实际客户来源，工程用途未准入。';
document.getElementById('exports').replaceChildren();for(const [name,file] of [['完整结果 JSON','screening.json'],['候选 GeoJSON','candidates.geojson'],['勘测连接 CSV','connections.csv'],['工程补数任务 CSV','engineering_data_tasks.csv']]){const a=document.createElement('a');a.href='真实试点结果/'+r.screening_id+'/'+file;a.textContent=name;a.setAttribute('download','');document.getElementById('exports').append(a)}
visibility();}
function visibility(){document.querySelectorAll('input[data-layer]').forEach(c=>{const g=document.querySelector('g[data-layer="'+c.dataset.layer+'"]');if(g)g.style.display=c.checked?'':'none'})}
document.querySelectorAll('input[data-layer]').forEach(c=>c.addEventListener('change',visibility));pilot.addEventListener('change',draw);draw();
</script></html>'''
