apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: probe-server-allow-authorized
  namespace: gda-metadata-network-policy-rehearsal
  labels:
    app.kubernetes.io/part-of: gda-metadata-network-policy-rehearsal
spec:
  podSelector:
    matchLabels:
      role: server
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: allowed
      ports:
        - protocol: TCP
          port: 8080
