apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gda-metadata-backup-repository
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - minio.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gda-metadata-fabric-backup-repository
      gda.openai.com/environment: local-backup-rehearsal
    includeSelectors: false
