apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gis-data-agent.fullname" . }}-env
  labels:
    {{- include "gis-data-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
