apiVersion: v1
kind: Service
metadata:
  name: {{ include "gis-data-agent.fullname" . }}
  labels:
    {{- include "gis-data-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "gis-data-agent.selectorLabels" . | nindent 4 }}
