import { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;

export default function DigitalReadinessTab() {
  const { t, i18n } = useTranslation();
  const [overview, setOverview] = useState<Row | null>(null); const [caps, setCaps] = useState<Row[]>([]); const [channels, setChannels] = useState<Row>({}); const [gate, setGate] = useState<Row>({}); const [message, setMessage] = useState('');
  const load = async () => { try { const headers = getLocaleHeaders(); const responses = await Promise.all(['overview', 'platform-capabilities', 'infrastructure-channels', 'uwm-gate'].map((part) => fetch(`/api/uwm/digital-readiness/${part}`, { credentials: 'include', headers }))); const data = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(data.find((item) => item.error)?.error || t('readinessPanels.digital.errors.unavailable')); setOverview(data[0]); setCaps(data[1].platform_capabilities || []); setChannels(data[2].infrastructure_channels || {}); setGate(data[3].uwm_gate || {}); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : t('readinessPanels.digital.errors.unavailable')); } };
  useEffect(() => { void load(); }, [i18n.resolvedLanguage]); const list = (value: Row) => Object.entries(value).map(([name, item]) => `${name}:${String((item as Row)?.status ?? item)}`).join(' · ') || t('readinessPanels.common.none');
  return <div className="traditional-livability-tab"><div className="traditional-panel"><div className="traditional-panel-title"><strong>{t('readinessPanels.digital.title')}</strong><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} />{t('readinessPanels.common.refresh')}</button></div><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.digital.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}<div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.digital.kpis.platform')}</span><strong>{overview?.summary?.platform_capability_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.digital.kpis.verified')}</span><strong>{overview?.summary?.verified_platform_capability_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.digital.kpis.channels')}</span><strong>{overview?.summary?.infrastructure_channel_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.digital.kpis.available')}</span><strong>{overview?.summary?.available_infrastructure_channel_count ?? '-'}</strong></div></div><h4>{t('readinessPanels.digital.sections.capabilities')}</h4><p>{caps.map((item) => `${item.capability_id}:${item.technology_route}`).join(' · ') || t('readinessPanels.common.none')}</p><h4>{t('readinessPanels.digital.sections.channels')}</h4><p>{list(channels)}</p><h4>{t('readinessPanels.digital.sections.gate')}</h4><p>{list(gate.mechanisms || {})}</p><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.digital.finalWarning')}</div></div></div>;
}
