import { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;

export default function FinancialReadinessTab() {
  const { t, i18n } = useTranslation();
  const [overview, setOverview] = useState<Row | null>(null); const [assets, setAssets] = useState<Row[]>([]); const [channels, setChannels] = useState<Row>({}); const [gate, setGate] = useState<Row>({}); const [message, setMessage] = useState('');
  const load = async () => { try { setMessage(''); const headers = getLocaleHeaders(); const responses = await Promise.all(['overview', 'evidence-assets', 'financial-channels', 'calculation-gate'].map((part) => fetch(`/api/uwm/financial-readiness/${part}`, { credentials: 'include', headers }))); const data = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(data.find((item) => item.error)?.error || t('readinessPanels.financial.errors.unavailable')); setOverview(data[0]); setAssets(data[1].evidence_assets || []); setChannels(data[2].financial_channels || {}); setGate(data[3]); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : t('readinessPanels.financial.errors.unavailable')); } };
  useEffect(() => { void load(); }, [i18n.resolvedLanguage]); const list = (value: Row) => Object.entries(value).map(([name, item]) => `${name}:${String((item as Row)?.status ?? item)}`).join(' · ') || t('readinessPanels.common.none');
  return <div className="traditional-livability-tab"><div className="traditional-panel"><div className="traditional-panel-title"><strong>{t('readinessPanels.financial.title')}</strong><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} />{t('readinessPanels.common.refresh')}</button></div><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.financial.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}<div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.financial.kpis.assets')}</span><strong>{overview?.summary?.evidence_asset_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.financial.kpis.channels')}</span><strong>{overview?.summary?.financial_channel_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.financial.kpis.available')}</span><strong>{overview?.summary?.available_financial_channel_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.financial.kpis.computed')}</span><strong>{overview?.summary?.computed_financial_output_count ?? '-'}</strong></div></div><h4>{t('readinessPanels.financial.sections.assets')}</h4><p>{assets.map((item) => `${item.title}:${item.asset_class}/${item.execution_status}`).join(' · ') || t('readinessPanels.common.none')}</p><h4>{t('readinessPanels.financial.sections.channels')}</h4><p>{list(channels)}</p><h4>{t('readinessPanels.financial.sections.calculation')}</h4><p>{list(gate.calculation_gate?.mechanisms || {})}</p><h4>{t('readinessPanels.financial.sections.handoff')}</h4><p>{gate.uwm_handoff_gate?.status || '-'}: {t('readinessPanels.financial.handoff')}</p><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.financial.finalWarning')}</div></div></div>;
}
