import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, RefreshCw, Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;
const arrayOf = <T,>(value: unknown): T[] => Array.isArray(value) ? value as T[] : [];

export default function ImplementationRoadmapTab() {
  const { t, i18n } = useTranslation(); const [overview, setOverview] = useState<Row | null>(null); const [tasks, setTasks] = useState<Row[]>([]); const [domains, setDomains] = useState<Row>({}); const [gates, setGates] = useState<Row>({}); const [message, setMessage] = useState('');
  const load = async () => { try { setMessage(''); const headers = getLocaleHeaders(); const responses = await Promise.all(['overview', 'tasks', 'domains', 'gates'].map((part) => fetch(`/api/uwm/implementation-roadmap/${part}`, { credentials: 'include', headers }))); const data = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(data.find((item) => item.error)?.error || t('readinessPanels.implementation.errors.unavailable')); setOverview(data[0]); setTasks(arrayOf(data[1].tasks)); setDomains(data[2].domain_chains || {}); setGates(data[3].gates || {}); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : t('readinessPanels.implementation.errors.unavailable')); } };
  useEffect(() => { void load(); }, [i18n.resolvedLanguage]); const ranked = useMemo(() => [...tasks].sort((a, b) => Number(a.priority_rank) - Number(b.priority_rank)).slice(0, 18), [tasks]);
  return <div className="traditional-livability-tab"><div className="traditional-panel"><div className="traditional-panel-title"><strong>{t('readinessPanels.implementation.title')}</strong><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} />{t('readinessPanels.common.refresh')}</button></div><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.implementation.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}<div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.implementation.kpis.tasks')}</span><strong>{overview?.summary?.task_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.implementation.kpis.verified')}</span><strong>{overview?.summary?.verified_task_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.implementation.kpis.ready')}</span><strong>{overview?.summary?.ready_task_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.implementation.kpis.blocked')}</span><strong>{overview?.summary?.blocked_task_count ?? '-'}</strong></div></div><h4>{t('readinessPanels.implementation.sections.tasks')}</h4><div className="traditional-table-wrap"><table className="traditional-table"><thead><tr><th>{t('readinessPanels.implementation.table.priority')}</th><th>{t('readinessPanels.implementation.table.task')}</th><th>{t('readinessPanels.implementation.table.domain')}</th><th>{t('readinessPanels.implementation.table.phase')}</th><th>{t('readinessPanels.implementation.table.status')}</th></tr></thead><tbody>{ranked.map((item) => <tr key={item.task_id}><td>{item.priority_rank}</td><td>{item.task_id}</td><td>{item.domain}</td><td>{item.phase}</td><td>{t(`statusLabels.${item.status}`, { defaultValue: item.status })}</td></tr>)}</tbody></table></div><h4>{t('readinessPanels.implementation.sections.chains')}</h4><p>{Object.entries(domains).map(([name, value]) => `${name}: ${arrayOf<string>(value).join(' → ')}`).join(' · ') || t('readinessPanels.common.none')}</p><h4>{t('readinessPanels.implementation.sections.gates')}</h4><p>{arrayOf<string>(gates.status_machine).join(' / ')}; {t('readinessPanels.implementation.gates.automatic')}: {String(gates.automatic_in_progress)}; {t('readinessPanels.implementation.gates.languageModel')}: {String(gates.language_model_status_promotion)}</p><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.implementation.finalWarning')}</div></div></div>;
}
