import { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;

export default function ParcelStateReadinessTab() {
  const { t, i18n } = useTranslation(); const [overview, setOverview] = useState<Row | null>(null); const [assets, setAssets] = useState<Row[]>([]); const [channels, setChannels] = useState<Row>({}); const [gate, setGate] = useState<Row>({}); const [message, setMessage] = useState('');
  const load = async () => { try { setMessage(''); const headers = getLocaleHeaders(); const responses = await Promise.all(['overview', 'source-assets', 'state-channels', 'state-gate'].map((part) => fetch(`/api/uwm/parcel-state-readiness/${part}`, { credentials: 'include', headers }))); const data = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(data.find((item) => item.error)?.error || t('readinessPanels.parcelState.errors.unavailable')); setOverview(data[0]); setAssets(data[1].source_assets || []); setChannels(data[2].state_channels || {}); setGate(data[3].state_gate || {}); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : t('readinessPanels.parcelState.errors.unavailable')); } };
  useEffect(() => { void load(); }, [i18n.resolvedLanguage]); const list = (value: Row) => Object.entries(value).map(([name, item]) => `${name}:${String((item as Row)?.status ?? item)}`).join(' · ') || t('readinessPanels.common.none');
  return <div className="traditional-livability-tab"><div className="traditional-panel"><div className="traditional-panel-title"><strong>{t('readinessPanels.parcelState.title')}</strong><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} />{t('readinessPanels.common.refresh')}</button></div><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.parcelState.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}<div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.parcelState.kpis.assets')}</span><strong>{overview?.summary?.source_asset_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.parcelState.kpis.features')}</span><strong>{overview?.summary?.audited_feature_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.parcelState.kpis.nodes')}</span><strong>{overview?.summary?.materialized_state_node_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.parcelState.kpis.transitions')}</span><strong>{overview?.summary?.observed_transition_count ?? '-'}</strong></div></div><h4>{t('readinessPanels.parcelState.sections.assets')}</h4><p>{assets.map((item) => `${item.title}:${item.asset_role}, fields=${(item.fields || []).join('/') || '-'}, materialised=${String(item.source_rows_materialized)}`).join(' · ') || t('readinessPanels.common.none')}</p><h4>{t('readinessPanels.parcelState.sections.channels')}</h4><p>{list(channels)}</p><h4>{t('readinessPanels.parcelState.sections.gate')}</h4><p>{list(gate.mechanisms || {})}</p><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.parcelState.finalWarning')}</div></div></div>;
}
