import { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;

export default function PopulationDemographicReadinessTab() {
  const { t, i18n } = useTranslation(); const [overview, setOverview] = useState<Row | null>(null); const [products, setProducts] = useState<Row[]>([]); const [channels, setChannels] = useState<Row>({}); const [gate, setGate] = useState<Row>({}); const [message, setMessage] = useState('');
  const load = async () => { try { setMessage(''); const headers = getLocaleHeaders(); const responses = await Promise.all(['overview', 'evidence-products', 'demographic-channels', 'population-gate'].map((part) => fetch(`/api/uwm/population-demographic-readiness/${part}`, { credentials: 'include', headers }))); const data = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(data.find((item) => item.error)?.error || t('readinessPanels.population.errors.unavailable')); setOverview(data[0]); setProducts(data[1].evidence_products || []); setChannels(data[2].demographic_channels || {}); setGate(data[3].population_gate || {}); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : t('readinessPanels.population.errors.unavailable')); } };
  useEffect(() => { void load(); }, [i18n.resolvedLanguage]); const list = (value: Row) => Object.entries(value).map(([name, item]) => `${name}:${String((item as Row)?.status ?? item)}`).join(' · ') || t('readinessPanels.common.none');
  return <div className="traditional-livability-tab"><div className="traditional-panel"><div className="traditional-panel-title"><strong>{t('readinessPanels.population.title')}</strong><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} />{t('readinessPanels.common.refresh')}</button></div><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.population.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}<div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.population.kpis.products')}</span><strong>{overview?.summary?.evidence_product_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.population.kpis.current')}</span><strong>{overview?.summary?.authoritative_current_population ?? t('readinessPanels.common.unavailable')}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.population.kpis.forecast')}</span><strong>{overview?.summary?.forecast_population ?? t('readinessPanels.common.unavailable')}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.population.kpis.nodes')}</span><strong>{overview?.summary?.materialized_population_state_count ?? '-'}</strong></div></div><h4>{t('readinessPanels.population.sections.products')}</h4><p>{products.map((item) => `${item.product_id}:${item.record_count ?? '-'}, ${item.observation_year}, ${item.spatial_grain}`).join(' · ') || t('readinessPanels.common.none')}</p><h4>{t('readinessPanels.population.sections.channels')}</h4><p>{list(channels)}</p><h4>{t('readinessPanels.population.sections.gate')}</h4><p>{list(gate.mechanisms || {})}</p><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.population.finalWarning')}</div></div></div>;
}
