import { useEffect, useState } from 'react';
import { AlertTriangle, Map, RefreshCw, Search, Shield, TriangleAlert } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;
const TARGET_NODE = '\u6c5f\u5317\u533a|\u89c2\u97f3\u6865\u8857\u9053|653';

export default function ResilienceWorldModelTab() {
  const { t, i18n } = useTranslation();
  const [overview, setOverview] = useState<Row | null>(null); const [gates, setGates] = useState<Row>({}); const [nodes, setNodes] = useState<Row[]>([]); const [nodeId, setNodeId] = useState(TARGET_NODE); const [detail, setDetail] = useState<Row | null>(null); const [hazard, setHazard] = useState('flood'); const [intervention, setIntervention] = useState('evacuation_route'); const [scenario, setScenario] = useState<Row | null>(null); const [search, setSearch] = useState(TARGET_NODE); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const localizedFetchInit = () => ({ credentials: 'include' as const, headers: getLocaleHeaders() });
  const loadOverview = async () => { const responses = await Promise.all(['overview', 'gates'].map((name) => fetch(`/api/uwm/resilience-kernel/${name}`, localizedFetchInit()))); const payloads = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(payloads.find((payload) => payload.error)?.error || t('readinessPanels.resilience.errors.kernelUnavailable')); setOverview(payloads[0]); setGates(payloads[1].evidence_gates || {}); };
  const loadNodes = async (query = search) => { const response = await fetch(`/api/uwm/resilience-kernel/nodes?search=${encodeURIComponent(query)}&limit=100`, localizedFetchInit()); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || t('readinessPanels.resilience.errors.nodesFailed')); setNodes(Array.isArray(payload.nodes) ? payload.nodes : []); };
  const loadDetail = async (selected = nodeId) => { const response = await fetch(`/api/uwm/resilience-kernel/nodes/${encodeURIComponent(selected)}`, localizedFetchInit()); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || t('readinessPanels.resilience.errors.stateFailed')); setDetail(payload); setScenario(null); };
  const initialize = async () => { setLoading(true); setMessage(''); try { await Promise.all([loadOverview(), loadNodes(TARGET_NODE), loadDetail(TARGET_NODE)]); } catch (error) { setMessage(error instanceof Error ? error.message : t('readinessPanels.resilience.errors.kernelUnavailable')); } finally { setLoading(false); } };
  const selectNode = async (selected: string) => { setNodeId(selected); setSearch(selected); setLoading(true); setMessage(''); try { await loadDetail(selected); } catch (error) { setMessage(error instanceof Error ? error.message : t('readinessPanels.resilience.errors.stateFailed')); } finally { setLoading(false); } };
  const checkScenario = async () => { setLoading(true); setMessage(''); try { const response = await fetch('/api/uwm/resilience-kernel/scenario-readiness', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json', ...getLocaleHeaders() }, body: JSON.stringify({ node_id: nodeId, hazard_type: hazard, intervention_type: intervention }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || t('readinessPanels.resilience.errors.scenarioFailed')); setScenario(payload); window.__handleMapUpdate?.(payload.map_payload); } catch (error) { setMessage(error instanceof Error ? error.message : t('readinessPanels.resilience.errors.scenarioFailed')); } finally { setLoading(false); } };
  useEffect(() => { void initialize(); }, [i18n.resolvedLanguage]);
  const node = detail?.node || {}; const network = node.network_context || {}; const services = node.public_service_context || {}; const emergency = node.emergency_facility_context || {};
  return <div className="traditional-livability-tab" data-testid="resilience-kernel-panel"><div className="traditional-panel">
    <div className="traditional-panel-title"><strong>{t('readinessPanels.resilience.title')}</strong><button className="secondary-button" onClick={() => void initialize()} disabled={loading}><RefreshCw size={14} />{t('readinessPanels.resilience.refresh')}</button></div>
    <div className="traditional-message error"><Shield size={15} />{t('readinessPanels.resilience.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}
    <div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.stateNodes')}</span><strong>{overview?.summary?.state_node_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.edges')}</span><strong>{overview?.summary?.graph_edge_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.evidenceGates')}</span><strong>{overview?.summary?.evidence_gate_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.mechanisms')}</span><strong>{overview?.summary?.open_transition_mechanism_count ?? '-'}</strong></div></div>
    <div className="traditional-form-grid"><label>{t('readinessPanels.resilience.sections.search')}<div className="traditional-inline-actions"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('readinessPanels.resilience.placeholders.search')} /><button className="secondary-button" onClick={() => void loadNodes()} disabled={loading}><Search size={14} />{t('readinessPanels.resilience.actions.find')}</button></div></label><label>{t('readinessPanels.resilience.sections.results')}<select value={nodeId} onChange={(event) => void selectNode(event.target.value)}>{!nodes.some((item) => item.node_id === nodeId) && <option value={nodeId}>{nodeId}</option>}{nodes.map((item) => <option key={item.node_id} value={item.node_id}>{item.node_id}</option>)}</select></label></div>
    {detail && <><h4>{t('readinessPanels.resilience.sections.context')}</h4><div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.roadSegments')}</span><strong>{network.road_segment_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.roadLength')}</span><strong>{Number(network.road_length_km || 0).toFixed(2)}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.accessibility')}</span><strong>{Number(network.service_accessibility_score || 0).toFixed(3)}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.servicePoints')}</span><strong>{services.service_point_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.facilities')}</span><strong>{emergency.observed_facility_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.resilience.kpis.responseTime')}</span><strong>{String(Boolean(emergency.response_time_claim))}</strong></div></div><button className="secondary-button" onClick={() => window.__handleMapUpdate?.(detail.map_payload)}><Map size={14} />{t('readinessPanels.resilience.actions.locate')}</button></>}
    <h4>{t('readinessPanels.resilience.sections.scenario')}</h4><div className="traditional-form-grid"><label>{t('readinessPanels.resilience.labels.hazard')}<select value={hazard} onChange={(event) => setHazard(event.target.value)}>{Object.entries(t('readinessPanels.resilience.hazards', { returnObjects: true }) as Record<string, string>).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{t('readinessPanels.resilience.labels.intervention')}<select value={intervention} onChange={(event) => setIntervention(event.target.value)}>{Object.entries(t('readinessPanels.resilience.interventions', { returnObjects: true }) as Record<string, string>).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <button className="primary-button" onClick={() => void checkScenario()} disabled={!detail || loading}>{t('readinessPanels.resilience.actions.check')}</button>{scenario && <div className="traditional-message error" data-testid="resilience-scenario-blocked"><TriangleAlert size={16} /><div><strong>{t('readinessPanels.resilience.labels.blocked')}</strong><br />{scenario.claim_boundary}<br /><span>{t('readinessPanels.resilience.labels.missingEvidence')}:</span><ul>{(scenario.required_evidence || []).map((item: string) => <li key={item}>{item}</li>)}</ul></div></div>}
    <h4>{t('readinessPanels.resilience.sections.gates')}</h4><p>{Object.entries(gates).map(([key, value]: [string, any]) => `${key}:${t(`statusLabels.${String(value.status)}`, { defaultValue: String(value.status) })}`).join(' · ') || t('readinessPanels.common.none')}</p>
  </div></div>;
}
