import { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Shield } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getLocaleHeaders } from '../../i18n';

type Row = Record<string, any>;

export default function SpatialScopeRegistryTab() {
  const { t, i18n } = useTranslation(); const [overview, setOverview] = useState<Row | null>(null); const [registry, setRegistry] = useState<Row>({}); const [diagnostics, setDiagnostics] = useState<Row>({}); const [units, setUnits] = useState<Row[]>([]); const [message, setMessage] = useState('');
  const load = async () => { try { setMessage(''); const headers = getLocaleHeaders(); const responses = await Promise.all(['overview', 'scope-registry', 'diagnostics', 'spatial-units'].map((part) => fetch(`/api/uwm/spatial-scope-registry/${part}`, { credentials: 'include', headers }))); const data = await Promise.all(responses.map((response) => response.json())); if (responses.some((response) => !response.ok)) throw new Error(data.find((item) => item.error)?.error || t('readinessPanels.spatialScope.errors.unavailable')); setOverview(data[0]); setRegistry(data[1].scope_registry || {}); setDiagnostics(data[2].diagnostics || {}); setUnits(data[3].spatial_units || []); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : t('readinessPanels.spatialScope.errors.unavailable')); } };
  useEffect(() => { void load(); }, [i18n.resolvedLanguage]);
  return <div className="traditional-livability-tab"><div className="traditional-panel"><div className="traditional-panel-title"><strong>{t('readinessPanels.spatialScope.title')}</strong><button className="secondary-button" onClick={() => void load()}><RefreshCw size={14} />{t('readinessPanels.common.refresh')}</button></div><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.spatialScope.warning')}</div>{message && <div className="traditional-message error"><AlertTriangle size={15} />{message}</div>}<div className="traditional-kpi-grid"><div className="traditional-kpi"><span>{t('readinessPanels.spatialScope.kpis.units')}</span><strong>{overview?.summary?.spatial_unit_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.spatialScope.kpis.counties')}</span><strong>{overview?.summary?.county_name_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.spatialScope.kpis.fragile')}</span><strong>{overview?.summary?.fragile_unit_count ?? '-'}</strong></div><div className="traditional-kpi"><span>{t('readinessPanels.spatialScope.kpis.validated')}</span><strong>{overview?.summary?.topology_validated_unit_count ?? '-'}</strong></div></div><h4>{t('readinessPanels.spatialScope.sections.registry')}</h4><p>{t('readinessPanels.spatialScope.labels.crs')}: {registry.crs || '-'} · {t('readinessPanels.spatialScope.labels.bounds')}: {(registry.derived_dataset_bounds || []).join(', ') || '-'} · {t('readinessPanels.spatialScope.labels.adjacency')}: {registry.kernel_adjacency_requirement || '-'}</p><h4>{t('readinessPanels.spatialScope.sections.diagnostics')}</h4><p>{t('readinessPanels.spatialScope.labels.historical')}: {(diagnostics.historical_county_names || []).join(', ') || t('readinessPanels.spatialScope.labels.none')} · {t('readinessPanels.spatialScope.labels.empty')}: {diagnostics.empty_geometry_count ?? '-'} · {t('readinessPanels.spatialScope.labels.duplicate')}: {diagnostics.duplicate_hierarchy_label_count ?? '-'} · {t('readinessPanels.spatialScope.labels.invalid')}: {diagnostics.invalid_coordinate_range_count ?? '-'}</p><h4>{t('readinessPanels.spatialScope.sections.samples')}</h4><p>{units.slice(0, 12).map((item) => `${item.county}/${item.township}:${item.unit_id}`).join(' · ') || t('readinessPanels.common.none')}</p><div className="traditional-message error"><Shield size={15} />{t('readinessPanels.spatialScope.finalWarning')}</div></div></div>;
}
