WITH bounds AS (
    SELECT ST_Transform(
        ST_MakeEnvelope(54.2971553, 24.2810331, 54.7659108, 24.601854, 4326),
        32640
    ) AS geom
), inventory AS (
    SELECT
        'pipeline'::text AS asset_role,
        COUNT(*)::bigint AS total_count,
        COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom, b.geom))::bigint AS target_count,
        COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom, b.geom))::bigint AS target_geom_count,
        COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom)::bigint AS target_empty_geom_count,
        COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom, b.geom) AND ST_SRID(t.geom) <> 32640)::bigint AS target_wrong_srid_count,
        COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom, b.geom) AND NULLIF(BTRIM(t.unitid), '') IS NOT NULL)::bigint AS target_unitid_present_count,
        COUNT(DISTINCT NULLIF(BTRIM(t.unitid), '')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom, b.geom))::bigint AS target_unitid_distinct_count,
        COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom, b.geom) AND NULLIF(BTRIM(t.uid), '') IS NOT NULL)::bigint AS target_uid_present_count,
        COUNT(DISTINCT NULLIF(BTRIM(t.uid), '')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom, b.geom))::bigint AS target_uid_distinct_count
    FROM layer.st_pipeline t CROSS JOIN bounds b
    UNION ALL
    SELECT 'inlet', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_inlet t CROSS JOIN bounds b
    UNION ALL
    SELECT 'catchbasin', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_catchbasin t CROSS JOIN bounds b
    UNION ALL
    SELECT 'sw_node', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_sw_node t CROSS JOIN bounds b
    UNION ALL
    SELECT 'sw_junction', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_sw_junction t CROSS JOIN bounds b
    UNION ALL
    SELECT 'outfall', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_outfall t CROSS JOIN bounds b
    UNION ALL
    SELECT 'ps_pump', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_ps_pump t CROSS JOIN bounds b
    UNION ALL
    SELECT 'pumpingstationstructure', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_sw_pumpingstationstructure t CROSS JOIN bounds b
    UNION ALL
    SELECT 'reservoirstructure', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_sw_reservoirstructure t CROSS JOIN bounds b
    UNION ALL
    SELECT 'soakaway', COUNT(*), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom IS NOT NULL AND t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE ST_IsEmpty(t.geom) AND t.geom && b.geom), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND ST_SRID(t.geom) <> 32640), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.unitid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.unitid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)), COUNT(*) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom) AND NULLIF(BTRIM(t.uid),'') IS NOT NULL), COUNT(DISTINCT NULLIF(BTRIM(t.uid),'')) FILTER (WHERE t.geom && b.geom AND ST_Intersects(t.geom,b.geom)) FROM layer.st_soakaway t CROSS JOIN bounds b
)
SELECT * FROM inventory ORDER BY asset_role;
