apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gis-agent

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: gis-data-agent
  app.kubernetes.io/managed-by: kustomize
