apiVersion: v1
kind: Service
metadata:
  name: martin
  namespace: gis-agent
  labels:
    app: martin
spec:
  selector:
    app: martin
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
