apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gda-metadata-sandbox
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - postgresql.yaml
  - opensearch.yaml
  - gravitino.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gda-metadata-fabric-sandbox
      gda.openai.com/environment: foundation-sandbox
    includeSelectors: false
