apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-openmetadata-postgresql
  namespace: gda-metadata-sandbox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-gravitino-postgresql
  namespace: gda-metadata-sandbox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-opensearch
  namespace: gda-metadata-sandbox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-gravitino
  namespace: gda-metadata-sandbox
automountServiceAccountToken: false
