apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gda-agentops-sandbox

resources:
  - namespace.yaml
  - postgres.yaml
  - temporal.yaml
  - worker.yaml
  - discovery-worker.yaml
  - networkpolicy.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: gis-data-agent
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/environment-profile: temporal-agentops-sandbox
