apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gis-agent

resources:
  - worker.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml
  - alertmanager-config.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: gis-agent-approval-notification-dashboard
    files:
      - approval-case-operations.json=dashboards/approval-case-operations.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: ApprovalCase Operations

generatorOptions:
  disableNameSuffixHash: true

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: gis-data-agent
      app.kubernetes.io/managed-by: kustomize
