from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from data_agent.uwm.resilience_kernel import build_resilience_kernel_product
def build_product(*,graph_path:Path,safety_path:Path,roadmap_path:Path,output_dir:Path):
 g=json.loads(graph_path.read_text());s=json.loads(safety_path.read_text());r=json.loads(roadmap_path.read_text());safety={x['admin_unit_id']:x for x in s['admin_units']};nodes=[]
 for x in g['mobility_nodes']:
  row=safety.get(x['unit_id'],{});nodes.append({'node_id':x['unit_id'],'admin_unit_id':x['unit_id'],'admin_name':f"{x.get('county')}/{x.get('township')}",'network_context':{'road_segment_count':x.get('road_segment_count'),'road_length_km':x.get('road_length_km'),'service_accessibility_score':x.get('service_accessibility_score')},'public_service_context':{'service_point_count':x.get('service_point_count'),'essential_service_count':x.get('essential_service_count')},'emergency_facility_context':row.get('public_safety_facility_context'),'environment_context':{'air_quality_context':row.get('air_quality_context'),'meteorology_context':row.get('meteorology_context')},'evidence_coverage':row.get('evidence_coverage'),'source_trace':[str(graph_path),str(safety_path)]})
 edges=[{'source_node_id':x['source_unit_id'],'target_node_id':x['target_unit_id'],'edge_type':'administrative_boundary_adjacency','edge_provenance':'full_admin_mobility_graph.boundary_adjacent','shared_boundary_or_network_basis':'verified_boundary_adjacent_flag','propagation_parameter':None} for x in g['mobility_edges'] if x.get('boundary_adjacent')]
 chain=r['domain_chains']['resilience'];p=build_resilience_kernel_product(nodes=nodes,edges=edges,dependency_chain=chain,source_artifacts=[str(graph_path),str(safety_path),str(roadmap_path)]);p['summary'].update({'source_graph_node_count':g['node_count'],'source_graph_edge_count':g['edge_count'],'boundary_adjacency_edge_count':len(edges),'dependency_task_count':len(chain)});write(p,output_dir);return p
def write(p,out):
 out.mkdir(parents=True,exist_ok=True);bid=p['bundle_id'];payloads={'overview.json':{k:v for k,v in p.items() if k not in {'state','graph','evidence_gates','current_rollout','dependency_chain'}},'state.json':{'schema':'uwm.resilience_state.v1','bundle_id':bid,'state':p['state']},'graph.json':{'schema':'uwm.resilience_graph.v1','bundle_id':bid,'edges':p['graph']},'evidence_gates.json':{'schema':'uwm.resilience_evidence_gates.v1','bundle_id':bid,'evidence_gates':p['evidence_gates']},'current_rollout.json':{'schema':'uwm.resilience_rollout.v1','bundle_id':bid,'current_rollout':p['current_rollout']},'dependency_chain.json':{'schema':'uwm.resilience_dependency_chain.v1','bundle_id':bid,'dependency_chain':p['dependency_chain']},'map.json':{'schema':'uwm.resilience_map.v1','bundle_id':bid,'layers':[{'name':'韧性状态节点','type':'geojson','geojsonData':{'type':'FeatureCollection','features':[{'type':'Feature','geometry':None,'properties':{'node_id':x['node_id'],'admin_name':x['admin_name']}} for x in p['state']]}}]}}
 for n,x in payloads.items():tmp=out/f'.{n}.tmp';tmp.write_text(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')));tmp.replace(out/n)
def main():
 q=argparse.ArgumentParser();q.add_argument('--graph',type=Path,required=True);q.add_argument('--safety',type=Path,required=True);q.add_argument('--roadmap',type=Path,required=True);q.add_argument('--output-dir',type=Path,required=True);a=q.parse_args();x=build_product(graph_path=a.graph,safety_path=a.safety,roadmap_path=a.roadmap,output_dir=a.output_dir);print(json.dumps({'bundle_id':x['bundle_id'],'summary':x['summary']},ensure_ascii=False))
if __name__=='__main__':main()
