#!/usr/bin/env python3
"""Run a TWM state snapshot lakehouse publish plan with Spark, Iceberg and Sedona."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def main() -> int:
    args = parse_args()
    plan = json.loads(Path(args.plan).read_text(encoding="utf-8"))
    report = run_publish_plan(plan)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
    return 0 if report.get("status") == "pass" else 2


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", required=True, help="Path to territory_world_model.state_snapshot_lakehouse_publish_plan.v1 JSON")
    parser.add_argument("--output", required=True, help="Path for the execution report JSON")
    return parser.parse_args()


def run_publish_plan(plan: dict[str, Any]) -> dict[str, Any]:
    spark = build_spark(plan)
    try:
        publish_results = [run_iceberg_publish_spec(spark, spec) for spec in plan.get("iceberg_publish_specs", [])]
        index_results = [run_sedona_index_spec(spark, spec) for spec in plan.get("sedona_spatial_index_specs", [])]
        iceberg_gate = snapshot_gate(publish_results)
        sedona_gate = index_gate(index_results, len(plan.get("sedona_spatial_index_specs", [])))
        status = "pass" if iceberg_gate["status"] == "pass" and sedona_gate["status"] == "pass" else "blocked"
        return {
            "schema": "territory_world_model.state_snapshot_lakehouse_publish_execution.v1",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "status": status,
            "state_version_id": plan.get("state_version_id", ""),
            "project_id": plan.get("project_id", ""),
            "iceberg_publish_results": publish_results,
            "sedona_spatial_index_results": index_results,
            "validation_gates": {
                "iceberg_snapshot_gate": iceberg_gate,
                "sedona_spatial_index_gate": sedona_gate,
                "consumer_switch_gate": {
                    "status": "pass" if status == "pass" else "blocked",
                    "required_gates": ["iceberg_snapshot_gate", "sedona_spatial_index_gate"],
                },
            },
            "claim_boundary": "Spark execution report generated by twm_state_snapshot_lakehouse_publish_job.py.",
        }
    finally:
        spark.stop()


def build_spark(plan: dict[str, Any]):
    from sedona.spark import SedonaContext

    builder = SedonaContext.builder().appName("twm-state-snapshot-lakehouse-publish")
    for key, value in spark_conf_from_plan(plan).items():
        builder = builder.config(key, value)
    spark = builder.getOrCreate()
    SedonaContext.create(spark)
    return spark


def spark_conf_from_plan(plan: dict[str, Any]) -> dict[str, str]:
    for spec in plan.get("iceberg_publish_specs", []):
        conf = spec.get("spark_conf")
        if isinstance(conf, dict) and conf:
            return {str(key): str(value) for key, value in conf.items()}
    return {}


def run_iceberg_publish_spec(spark: Any, spec: dict[str, Any]) -> dict[str, Any]:
    table = str(spec.get("table_identifier") or "")
    expected = int(spec.get("row_count") or 0)
    spark.sql(str(spec.get("ddl") or ""))
    rows_written = spark.table(table).count() if table else -1
    snapshot_id = latest_snapshot_id(spark, table)
    row_count_status = "pass" if rows_written == expected else "fail"
    return {
        "artifact": spec.get("artifact", ""),
        "table_identifier": table,
        "returncode": 0 if snapshot_id and row_count_status == "pass" else 1,
        "snapshot_id": snapshot_id,
        "expected_row_count": expected,
        "rows_written": rows_written,
        "row_count_status": row_count_status,
        "status": "pass" if snapshot_id and row_count_status == "pass" else "fail",
    }


def run_sedona_index_spec(spark: Any, spec: dict[str, Any]) -> dict[str, Any]:
    output_table = str(spec.get("output_table") or "")
    spark.sql(str(spec.get("sql") or ""))
    rows_written = spark.table(output_table).count() if output_table else -1
    snapshot_id = latest_snapshot_id(spark, output_table)
    return {
        "artifact": spec.get("artifact", ""),
        "output_table": output_table,
        "returncode": 0 if snapshot_id else 1,
        "snapshot_id": snapshot_id,
        "rows_written": rows_written,
        "index_strategy": spec.get("index_strategy") or {},
        "status": "pass" if snapshot_id else "fail",
    }


def latest_snapshot_id(spark: Any, table_identifier: str) -> str:
    if not table_identifier:
        return ""
    try:
        rows = spark.sql(
            f"SELECT snapshot_id FROM {table_identifier}.snapshots ORDER BY committed_at DESC LIMIT 1"
        ).collect()
    except Exception:
        return ""
    return str(rows[0]["snapshot_id"]) if rows else ""


def snapshot_gate(results: list[dict[str, Any]]) -> dict[str, Any]:
    missing = [f"{item.get('artifact')}.snapshot_id" for item in results if not item.get("snapshot_id")]
    failed = [f"{item.get('artifact')}.row_count" for item in results if item.get("row_count_status") != "pass"]
    return {
        "status": "pass" if results and not missing and not failed else "blocked",
        "snapshot_count": sum(1 for item in results if item.get("snapshot_id")),
        "missing": missing,
        "failed": failed,
    }


def index_gate(results: list[dict[str, Any]], expected_count: int) -> dict[str, Any]:
    missing = [f"{item.get('artifact')}.snapshot_id" for item in results if not item.get("snapshot_id")]
    failed = [f"{item.get('artifact')}.execution" for item in results if item.get("status") != "pass"]
    return {
        "status": "pass" if expected_count > 0 and len(results) == expected_count and not missing and not failed else "blocked",
        "expected_index_count": expected_count,
        "completed_index_count": len(results),
        "missing": missing,
        "failed": failed,
    }


if __name__ == "__main__":
    raise SystemExit(main())
