apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gis-agent

resources:
  - worker.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml
  - alertmanager-config.yaml
  - networkpolicy.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: gis-data-agent
      app.kubernetes.io/managed-by: kustomize
