apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gis-agent-hydro-dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: hydro-api
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: desktop-worker
