apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-otel-collector
  namespace: gda-metadata-sandbox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-json-exporter
  namespace: gda-metadata-sandbox
automountServiceAccountToken: false
