apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gda-metadata-spark-object-store
resources:
  - namespace.yaml
  - runtime.yaml
  - spark-job.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gda-metadata-fabric-spark-object-store-interoperability
      gda.openai.com/environment: spark-object-store-interoperability-rehearsal
    includeSelectors: false
