apiVersion: v1
kind: ServiceAccount
metadata:
  name: recovery-openmetadata-postgresql
  namespace: gda-metadata-recovery-rehearsal
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recovery-gravitino-postgresql
  namespace: gda-metadata-recovery-rehearsal
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recovery-opensearch
  namespace: gda-metadata-recovery-rehearsal
automountServiceAccountToken: false
